# Generated by VisualGDB

LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE    := Caster
#VisualGDBAndroid: AutoUpdateSourcesInNextLine
LOCAL_SRC_FILES := Caster.cpp
LOCAL_C_INCLUDES := E:/vcpro/VideoChat/CasterTest/libevent \
E:/vcpro/VideoChat/CasterTest/libevent/include \
F:/android/android-ndk-r10/sources/cxx-stl/gnu-libstdc++/4.8/include \
F:\android\android-ndk-r10\sources\cxx-stl\gnu-libstdc++\4.8\libs\armeabi\include \
E:/vcpro/VideoChat/T
LOCAL_STATIC_LIBRARIES := 
LOCAL_SHARED_LIBRARIES := 
LOCAL_LDLIBS := libevent.a
LOCAL_CFLAGS := 
LOCAL_CPPFLAGS := 
LOCAL_LDFLAGS := -lz -lm -llog
include $(BUILD_SHARED_LIBRARY)
